import type { LevelConfig, QuestTemplate, DummyProfile } from './types'

export const LEVELS: LevelConfig[] = [
  { level: 1, name: '무너진 밤', minXP: 0, reward: null },
  { level: 2, name: '버틴 하루', minXP: 300, reward: null },
  { level: 3, name: '작은 변화', minXP: 800, reward: { contactCredits: 1 } },
  { level: 4, name: '숨 고르기', minXP: 1500, reward: null },
  { level: 5, name: '나를 위한 시간', minXP: 2500, reward: { contactCredits: 1, sincerityCards: 1 } },
  { level: 6, name: '다시 걷기', minXP: 4000, reward: null },
  { level: 7, name: '단단해지는 중', minXP: 6000, reward: { badge: '단단한 마음' } },
  { level: 8, name: '빛나기 시작', minXP: 8500, reward: { contactCredits: 1 } },
  { level: 9, name: '나를 사랑하는 중', minXP: 11500, reward: { priorityBoost: true } },
  { level: 10, name: '더 나은 나', minXP: 15000, reward: { badge: '더 나은 나', contactCredits: 2 } },
]

export const DAILY_QUEST_TEMPLATES: QuestTemplate[] = [
  {
    id: 'daily-water',
    title: '물 2L 마시기',
    description: '오늘 하루 물을 충분히 마셨나요? 나를 돌보는 가장 작은 시작.',
    type: 'daily',
    difficulty: 'easy',
    xp: 10,
    verificationType: 'text',
  },
  {
    id: 'daily-walk',
    title: '산책 20분',
    description: '바깥 공기를 마시며 걷기. 생각이 정리되는 시간.',
    type: 'daily',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'timer',
    timerSeconds: 1200,
  },
  {
    id: 'daily-journal',
    title: '감정 일기 작성',
    description: '오늘 느낀 감정을 짧게 기록해보세요. 판단 없이.',
    type: 'daily',
    difficulty: 'easy',
    xp: 10,
    verificationType: 'text',
  },
  {
    id: 'daily-no-sns',
    title: '전 애인 SNS 안 보기',
    description: '그냥 안 보는 날. 그게 다야.',
    type: 'daily',
    difficulty: 'easy',
    xp: 10,
    verificationType: 'text',
  },
  {
    id: 'daily-compliment',
    title: '오늘 나를 칭찬하기',
    description: '오늘 잘한 것 하나를 스스로 인정해보기.',
    type: 'daily',
    difficulty: 'easy',
    xp: 10,
    verificationType: 'text',
  },
  {
    id: 'daily-meal',
    title: '제대로 된 식사 하기',
    description: '인스턴트 말고, 진짜 밥 한 끼.',
    type: 'daily',
    difficulty: 'easy',
    xp: 10,
    verificationType: 'text',
  },
  {
    id: 'daily-sleep',
    title: '12시 전에 자기',
    description: '몸이 먼저 회복해야 마음도 회복된다.',
    type: 'daily',
    difficulty: 'easy',
    xp: 10,
    verificationType: 'text',
  },
]

export const WEEKLY_QUEST_TEMPLATES: QuestTemplate[] = [
  {
    id: 'weekly-exercise',
    title: '운동 인증',
    description: '이번 주 운동한 순간을 사진으로 남겨봐요.',
    type: 'weekly',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'photo',
  },
  {
    id: 'weekly-cafe',
    title: '혼자 카페 가기',
    description: '혼자서도 괜찮은 시간. 어색해도 괜찮아요.',
    type: 'weekly',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'photo',
  },
  {
    id: 'weekly-friend',
    title: '친구에게 연락하기',
    description: '요즘 연락 못 한 사람 한 명에게 먼저 연락해보기.',
    type: 'weekly',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'text',
  },
  {
    id: 'weekly-gift',
    title: '나를 위한 선물 사기',
    description: '작아도 괜찮아요. 나한테 뭔가 사주는 날.',
    type: 'weekly',
    difficulty: 'hard',
    xp: 35,
    verificationType: 'photo',
  },
  {
    id: 'weekly-clean',
    title: '방 청소하기',
    description: '공간이 정리되면 마음도 조금 가벼워져요.',
    type: 'weekly',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'photo',
  },
  {
    id: 'weekly-read',
    title: '책 20분 읽기',
    description: '핸드폰 내려두고, 책 한 권과 함께.',
    type: 'weekly',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'timer',
    timerSeconds: 1200,
  },
  {
    id: 'weekly-meditate',
    title: '명상 10분',
    description: '눈 감고 그냥 있어봐요. 아무것도 안 해도 괜찮아.',
    type: 'weekly',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'timer',
    timerSeconds: 600,
  },
]

export const LIFE_QUEST_TEMPLATES: QuestTemplate[] = [
  {
    id: 'life-travel',
    title: '혼자 여행 가기',
    description: '어디든 좋아요. 혼자 떠나는 첫 여행.',
    type: 'life',
    difficulty: 'big',
    xp: 60,
    verificationType: 'photo',
  },
  {
    id: 'life-hobby',
    title: '새로운 취미 시작하기',
    description: '전 애인이랑 함께 하던 것 말고, 나만의 것.',
    type: 'life',
    difficulty: 'big',
    xp: 60,
    verificationType: 'photo',
  },
  {
    id: 'life-stuff',
    title: '전 애인 물건 정리하기',
    description: '버려도, 박스에 넣어도 좋아요. 준비됐을 때.',
    type: 'life',
    difficulty: 'hard',
    xp: 35,
    verificationType: 'text',
  },
  {
    id: 'life-photo',
    title: '새로운 프로필 사진 찍기',
    description: '지금의 나로, 새로운 시작.',
    type: 'life',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'photo',
  },
  {
    id: 'life-30days',
    title: '30일 연속 회복 기록',
    description: '매일 앱을 켜고 기록한 30일. 대단한 일이에요.',
    type: 'life',
    difficulty: 'big',
    xp: 60,
    verificationType: 'none',
  },
  {
    id: 'life-cooking',
    title: '나를 위한 요리 해먹기',
    description: '배달 말고, 손수 만들어서 먹는 밥.',
    type: 'life',
    difficulty: 'normal',
    xp: 20,
    verificationType: 'photo',
  },
]

export const ALL_QUEST_TEMPLATES: QuestTemplate[] = [
  ...DAILY_QUEST_TEMPLATES,
  ...WEEKLY_QUEST_TEMPLATES,
  ...LIFE_QUEST_TEMPLATES,
]

export const DUMMY_PROFILES: DummyProfile[] = [
  {
    id: 'profile-1',
    name: '민준',
    age: 27,
    gender: 'male',
    location: '서울 마포구',
    avatarColor: '#7C9885',
    breakupDate: '2025-03-10',
    bio: '새벽에 혼자 걷는 걸 좋아해요. 요즘 운동 시작했어요.',
    interests: ['독서', '운동', '요리'],
    level: 2,
    xp: 450,
    completedQuestTitles: ['산책 20분', '물 2L 마시기'],
    preferredVibes: ['차분한', '공감 잘하는'],
    relationshipGoal: '가벼운 대화',
  },
  {
    id: 'profile-2',
    name: '지은',
    age: 25,
    gender: 'female',
    location: '서울 성동구',
    avatarColor: '#8E7C9E',
    breakupDate: '2025-02-14',
    bio: '혼자 카페 다니는 게 좋아졌어요. 영화도 혼자 보고.',
    interests: ['영화', '커피', '그림'],
    level: 3,
    xp: 950,
    completedQuestTitles: ['혼자 카페 가기', '나를 위한 선물 사기'],
    preferredVibes: ['다정한', '밝은'],
    relationshipGoal: '위로',
  },
  {
    id: 'profile-3',
    name: '서현',
    age: 29,
    gender: 'female',
    location: '경기 판교',
    avatarColor: '#C17F6E',
    breakupDate: '2025-01-20',
    bio: '갑자기 등산을 시작했어요. 이상하게 올라가면 생각이 비워져요.',
    interests: ['등산', '사진', '요가'],
    level: 4,
    xp: 1650,
    completedQuestTitles: ['운동 인증', '명상 10분', '방 청소하기'],
    preferredVibes: ['자기관리하는', '공감 잘하는'],
    relationshipGoal: '새로운 설렘',
  },
  {
    id: 'profile-4',
    name: '재원',
    age: 31,
    gender: 'male',
    location: '서울 강남구',
    avatarColor: '#6E8EA8',
    breakupDate: '2024-12-25',
    bio: '밥을 제때 먹는 것부터 다시 시작했어요.',
    interests: ['음악', '산책', '드라이브'],
    level: 3,
    xp: 820,
    completedQuestTitles: ['감정 일기 작성', '친구에게 연락하기'],
    preferredVibes: ['차분한', '웃긴'],
    relationshipGoal: '가벼운 대화',
  },
  {
    id: 'profile-5',
    name: '유나',
    age: 24,
    gender: 'female',
    location: '서울 송파구',
    avatarColor: '#A8856E',
    breakupDate: '2025-04-01',
    bio: '이제 막 회복 시작한 것 같아요. 그래도 오늘은 밥 먹었어요.',
    interests: ['넷플릭스', '베이킹', '고양이'],
    level: 1,
    xp: 80,
    completedQuestTitles: ['물 2L 마시기'],
    preferredVibes: ['다정한', '공감 잘하는'],
    relationshipGoal: '위로',
  },
  {
    id: 'profile-6',
    name: '현우',
    age: 28,
    gender: 'male',
    location: '인천 연수구',
    avatarColor: '#7A9E7E',
    breakupDate: '2025-01-05',
    bio: '요리를 배우기 시작했어요. 혼자 먹을 밥이어도 맛있게.',
    interests: ['요리', '게임', '운동'],
    level: 4,
    xp: 1800,
    completedQuestTitles: ['운동 인증', '나를 위한 요리 해먹기', '방 청소하기'],
    preferredVibes: ['밝은', '웃긴'],
    relationshipGoal: '진지한 관계',
  },
  {
    id: 'profile-7',
    name: '다은',
    age: 26,
    gender: 'female',
    location: '서울 노원구',
    avatarColor: '#9E8A7A',
    breakupDate: '2025-02-28',
    bio: '책을 다시 읽기 시작했어요. 예전엔 못 읽었는데.',
    interests: ['독서', '글쓰기', '카페'],
    level: 3,
    xp: 1100,
    completedQuestTitles: ['책 20분 읽기', '혼자 카페 가기'],
    preferredVibes: ['차분한', '공감 잘하는'],
    relationshipGoal: '가벼운 대화',
  },
  {
    id: 'profile-8',
    name: '승훈',
    age: 30,
    gender: 'male',
    location: '서울 용산구',
    avatarColor: '#7E8E9E',
    breakupDate: '2024-11-15',
    bio: '혼자 여행 다녀왔어요. 생각보다 나쁘지 않더라고요.',
    interests: ['여행', '사진', '커피'],
    level: 5,
    xp: 2700,
    completedQuestTitles: ['혼자 여행 가기', '새로운 프로필 사진 찍기'],
    preferredVibes: ['자기관리하는', '밝은'],
    relationshipGoal: '새로운 설렘',
  },
]

export const DAILY_MESSAGES = [
  '오늘도 여기 있는 것만으로 충분해요.',
  '잘 버텼어요. 오늘 하루.',
  '회복은 선형이 아니에요. 괜찮아요.',
  '조금씩, 나를 다시 찾는 중이에요.',
  '무너진 자리에서 다시 시작하는 것, 그게 용기예요.',
  '오늘도 나를 위해 열었네요. 잘했어요.',
  '지금 이 감정, 다 맞아요.',
  '완벽하지 않아도 돼요. 그냥 오늘을 살면 돼요.',
  '회복하는 사람은 강한 사람이에요.',
  '나를 잃은 게 아니에요. 찾는 중이에요.',
]

export const AI_FEEDBACK_BY_MOOD: Record<string, string[]> = {
  '좋아요': [
    '오늘 좋은 날이네요. 이 감정, 기억해두면 좋겠어요.',
    '좋은 하루가 계속 이어지길.',
  ],
  '평온해요': [
    '평온함도 회복의 일부예요. 잘 지내고 있어요.',
    '조용한 하루. 나쁘지 않죠.',
  ],
  '멍해요': [
    '멍한 날도 있어요. 억지로 뭔가 하지 않아도 돼요.',
    '가끔은 그냥 있는 것도 괜찮아요.',
  ],
  '외로워요': [
    '외로움을 느낀다는 건, 연결을 원한다는 거예요.',
    '혼자인 것과 외로운 건 달라요. 지금은 외롭지만, 혼자가 아니에요.',
  ],
  '슬퍼요': [
    '슬픔은 오래 가지 않아요. 지금은 느껴도 돼요.',
    '슬픔을 외면하지 않는 것도 용기예요.',
  ],
  '화나요': [
    '화가 났군요. 그 감정도 다 맞아요.',
    '화나는 날도 있죠. 잘 지나갈 거예요.',
  ],
  '불안해요': [
    '불안은 미래에 대한 관심이기도 해요. 지금 여기, 오늘에 집중해봐요.',
    '불안할 때일수록 지금 할 수 있는 작은 것 하나만 생각해봐요.',
  ],
}

export const SHOP_ITEMS = [
  {
    id: 'shop-contact-1',
    name: '연락 보내기 1회',
    description: '새로운 인연에게 먼저 다가갈 수 있어요.',
    price: 2900,
    icon: 'mail',
  },
  {
    id: 'shop-contact-3',
    name: '연락 보내기 3회',
    description: '더 많은 인연과 연결될 기회.',
    price: 6900,
    icon: 'mail',
    badge: 'BEST',
  },
  {
    id: 'shop-sincerity',
    name: '진심 카드 1장',
    description: '특별한 메시지를 전달할 수 있어요.',
    price: 1900,
    icon: 'heart',
  },
  {
    id: 'shop-priority',
    name: '우선 추천 1일',
    description: '오늘 하루 더 많은 사람에게 보여질 수 있어요.',
    price: 3900,
    icon: 'star',
  },
  {
    id: 'shop-view',
    name: '프로필 더 보기',
    description: '오늘의 추천 5명을 추가로 열람할 수 있어요.',
    price: 1900,
    icon: 'eye',
  },
]
